version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xlvk20o3e2iz"
s3_prefix = "sam-app-2"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectId=\"\" CodeDeployRole=\"\" Stage=\"develop\""
image_repositories = []
